### ISSUE TITLE
wget got a 404 error on storm-0.9.2-incubating.zip

### ISSUE THREAD

**Issue by chiptip** [viki-org/storm-docker#7]
2014/12/18 15:19:19 The command [/bin/sh -c wget -q -N http://mirror.reverse.net/pub/apache/incubator/storm/apache-storm-0.9.2-incubating/apache-storm-0.9.2-incubating.zip] returned a non-zero code: 8
make: **\* [build-base-storm-docker-container] Error 1

**Comment by yanhan** [comment]
Hi @chiptip , submit a pull request? I'll merge this in asap.
